sources= projectGame.cpp

all : projectGame.cpp

ProjectGame: $(sources:.cpp=.o)
		g++ -Wall -g -o $@ $^
%.o: %.cpp
	g++ -Wall -g -c -MMD -o $@ $<

-include $(sources:.cpp=.d)

clean:
	rm projectGame all
